using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum PlayerStats
{
    ROLLING_DICE, MOVING,MOVING_BACK,END_MOVING, CHOOSING_PATH, ANSWERING_QUESTION, STRATEGIC_CHOICE,DOING_PUZZLE ,END_TURN ,IDLE , DOING_EVENT, FINISHED_EVENT}
